import { App } from 'vue';
declare const install: (app: App) => void;
export * from './button';
export * from './card';
export * from './input';
export * from './loading';
export * from './drawer';
export * from './tips';
export * from './rate';
export * from './popup';
export * from './message';
export * from './pagination';
export * from './skeleton';
export * from './skeleton-item';
export * from './option';
export * from './select';
export * from './stepbar';
export * from './stepitem';
export * from './tabs';
export * from './tab';
export * from './switch';
export * from './radio';
export * from './radioGroup';
export * from './link';
export { install };
export default install;
